services:
  node1:
    image: threefolddev/ubuntu24.04
    volumes:
      - ${SSH_PUBKEY_PATH:-./authorized_keys}:/root/.ssh/authorized_keys
  node2:
    image: threefolddev/ubuntu24.04
    volumes:
      - ${SSH_PUBKEY_PATH:-./authorized_keys}:/root/.ssh/authorized_keys
  node3:
    image: threefolddev/ubuntu24.04
    volumes:
      - ${SSH_PUBKEY_PATH:-./authorized_keys}:/root/.ssh/authorized_keys
