---
- name: Deploy node-status-bot
  hosts: all
  become: yes
  vars:
    bot_install_dir: "/opt/node-status-bot"
    bot_venv_dir: "{{ bot_install_dir }}/venv"
    zinit_services_dir: "/etc/zinit"
    git_repo: "https://github.com/threefoldfoundation/node-status-bot.git"
    git_ref: "main" # Can be commit hash, tag, or branch name
    bot_token: "{{ bot_token | mandatory('bot_token must be specified!') }}"

  tasks:
    - name: Ensure system dependencies are installed
      apt:
        name:
          - python3-venv
          - python3-pip
          - build-essential
          - git
        state: present
        update_cache: yes

    - name: Clone repository and checkout specific ref
      git:
        repo: "{{ git_repo }}"
        dest: "{{ bot_install_dir }}"
        version: "{{ git_ref }}"
        force: yes
        update: yes
        depth: 0

    - name: Create Python virtual environment
      ansible.builtin.pip:
        name:
          - pip
          - setuptools
          - wheel
        virtualenv: "{{ bot_venv_dir }}"
        virtualenv_command: python3 -m venv
        state: present

    - name: Install Python dependencies
      ansible.builtin.pip:
        requirements: "{{ bot_install_dir }}/requirements.txt"
        virtualenv: "{{ bot_venv_dir }}"
        state: present

    - name: Ensure zinit services directory exists
      file:
        path: "{{ zinit_services_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create zinit service file for node-status-bot
      copy:
        dest: "{{ zinit_services_dir }}/node-status-bot.yaml"
        content: |
          exec: {{ bot_venv_dir }}/bin/python {{ bot_install_dir }}/node-status-bot.py {{ bot_token }} --rqlite-host localhost --rqlite-port 4001
          env:
            PYTHONUNBUFFERED: 1
        owner: root
        group: root
        mode: "0644"

    - name: Start node-status-bot service with zinit
      command: zinit monitor node-status-bot
      changed_when: false
